'use client';
import { useState } from 'react';
import { components, syntheticRaster } from '@/lib/playground-models';
const pixels=syntheticRaster(),colours=['#00d9ff','#ff719f','#aeb2ff','#9de0b8'];
export default function ConnectedComponents() {
  const [threshold,setThreshold]=useState(128),[min,setMin]=useState(4);
  const result=components(pixels,24,threshold,min);
  const groupOf=new Map(result.groups.flatMap((g,i)=>g.map(p=>[p,i] as const)));
  const kept=new Set(result.kept.flat());
  return <div className='demo-instrument'><div className='demo-toolbar'><div><p className='eyebrow'>FOUR-NEIGHBOUR BFS</p><h2>Pixels into regions.</h2></div><button className='button button-quiet' onClick={()=>{setThreshold(128);setMin(4);}}>Reset</button></div><div className='demo-sliders'><label>Threshold <strong>{threshold}</strong><input aria-label='Image threshold' type='range' min='1' max='255' value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><label>Minimum size <strong>{min} pixels</strong><input aria-label='Minimum component size' type='range' min='1' max='50' value={min} onChange={e=>setMin(Number(e.target.value))}/></label></div><div className='raster-pipeline'>{['Original','Threshold','Components','Size filter'].map((label,stage)=><figure key={label}><figcaption>{label}</figcaption><svg viewBox='0 0 240 160' role='img' aria-label={`${label}: synthetic grayscale raster`}>{pixels.map((v,i)=><rect key={i} x={i%24*10} y={Math.floor(i/24)*10} width='10' height='10' fill={stage===0?`rgb(${v},${v},${v})`:stage===1?v>=threshold?'#e4f3f4':'#091219':stage===2?groupOf.has(i)?colours[groupOf.get(i)!%4]:'#091219':kept.has(i)?colours[groupOf.get(i)!%4]:'#091219'}/>)}</svg></figure>)}</div><div className='lab-readouts'><div>DETECTED<strong>{result.groups.length}</strong></div><div>KEPT<strong>{result.kept.length}</strong></div><div>FOREGROUND PIXELS<strong>{result.kept.flat().length}</strong></div></div><p className='demo-status' role='status'>Component sizes: {result.groups.map(g=>g.length).join(', ')||'none'} · kept sizes: {result.kept.map(g=>g.length).join(', ')||'none'}</p><p className='evidence-caption'>Faithful TypeScript BFS recreation, not C++ or WebAssembly execution. Four orthogonal neighbours; pixels ≥ threshold; inclusive minimum size. New synthetic raster only. An independent visited set avoids mutating input. Threshold zero is intentionally excluded because the historical zero-as-visited approach cannot safely support it.</p></div>;
}
