'use client';
import { useRef, useState } from 'react';
import { catchWord, fallWords, initialWords } from '@/lib/playground-models';
import { useDemoClock } from './use-demo-clock';
import { DemoControls } from './controls';
export default function FallingWords() {
  const [state,setState]=useState(initialWords),[running,setRunning]=useState(false),[input,setInput]=useState(''),[speed,setSpeed]=useState(1),[message,setMessage]=useState('Ready.');
  const field=useRef<HTMLInputElement>(null);
  const {ref:demoRef,reduced,active}=useDemoClock(running,100,()=>setState(s=>fallWords(s,speed)));
  const reset=()=>{setState(initialWords());setRunning(false);setInput('');setMessage('Ready.');};
  return <div ref={demoRef} className='demo-instrument typing-demo'><div className='demo-toolbar'><div><p className='eyebrow'>WORDS IN MOTION</p><h2>Catch the next word.</h2></div><label>Speed<select aria-label='Word speed' value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={1}>1x</option><option value={2}>2x</option><option value={3}>3x</option></select></label></div><div className='lab-readouts'><div>SCORE<strong>{state.score}</strong></div><div>CAUGHT<strong>{state.caught}</strong></div><div>MISSED<strong>{state.missed}</strong></div></div><div className='word-field' aria-label='Falling word lanes'>{state.words.map((w,i)=><span key={i} className={`falling-word lane-${i}`} style={{top:`${Math.max(0,w.y)*.85}%`,visibility:w.y<0?'hidden':'visible'}}>{w.text}</span>)}<span className='word-floor'>CATCH LINE</span>{!running&&<span className='word-paused'>{state.caught+state.missed?'PAUSED':'READY'}</span>}</div><form className='word-form' onSubmit={e=>{e.preventDefault();if(!running)return;const next=catchWord(state,input);setState(next);setMessage(next===state?'No matching word.':`Caught ${input}: +${input.length}`);setInput('');}}><label htmlFor='word-input'>Word<input ref={field} id='word-input' value={input} autoComplete='off' autoCapitalize='none' spellCheck={false} onChange={e=>setInput(e.target.value)}/></label><button type='submit' className='button button-quiet' disabled={!running}>Catch</button></form><p className='demo-status' role='status'>{message}</p><DemoControls running={active} reduced={reduced} toggle={()=>{setRunning(!running);field.current?.focus();}} step={()=>{setRunning(false);setState(s=>fallWords(s,10));}} reset={reset}/><p className='evidence-caption'>2026 recreation. Exact matching and points by word length follow the original Score/FallingWord rules. Synthetic vocabulary and adjustable speed are new. Browser events replace Java workers; no original thread execution is implied.</p></div>;
}
