'use client';
import { useEffect, useState, useSyncExternalStore } from 'react';
import { ArrowLeft, ArrowRight, Pause, Play, RotateCcw } from 'lucide-react';
import recordings from '@/data/four-rooms-replay.json';
const subscribeMotion=(callback:()=>void)=>{const query=matchMedia('(prefers-reduced-motion: reduce)');query.addEventListener('change',callback);return()=>query.removeEventListener('change',callback);};
export function FourRoomsReplay() {
  const [mode,setMode]=useState(0);const [step,setStep]=useState(0);const [playing,setPlaying]=useState(false);
  const reduced=useSyncExternalStore(subscribeMotion,()=>matchMedia('(prefers-reduced-motion: reduce)').matches,()=>true);
  const recording=recordings[mode]; const count=recording.trace.length;
  const current=step?recording.trace[step-1]:null;
  const position=current?.position??recording.start;
  const running=playing&&step<count;
  useEffect(()=>{if(!running||reduced)return;const timer=setTimeout(()=>setStep(s=>Math.min(s+1,count)),180);return()=>clearTimeout(timer);},[running,step,count,reduced]);
  const path=[recording.start,...recording.trace.slice(0,step).map(s=>s.position)].map(([x,y])=>`${x*24+12},${y*24+12}`).join(' ');
  const reward=recording.trace.slice(0,step).reduce((sum,s)=>sum+s.reward,0);
  return <div className="engineering-tool interactive-lab"><div className="lab-toolbar"><p className="eyebrow">ACTUAL RECORDED AGENT / SEED42</p><div className="segmented" role="group" aria-label="Four Rooms environment">{recordings.map((r,i)=><button key={r.mode} aria-pressed={mode===i} onClick={()=>{setMode(i);setStep(0);setPlaying(false);}}>{r.mode}</button>)}</div></div><div className="rl-replay-layout"><svg viewBox="0 0 312 312" className="room-grid" role="img" aria-label={`${recording.mode} agent at ${position.join(', ')}, step ${step}`}>
    {recording.grid.flatMap((row,y)=>row.map((v,x)=><rect key={`${x}-${y}`} x={x*24} y={y*24} width="23" height="23" fill={v===-1?'#40515a':'#14262d'}/>))}<polyline points={path} fill="none" stroke="#c3be91" strokeWidth="2.5"/>{recording.packages.map(([x,y],i)=><rect key={i} x={x*24+6} y={y*24+6} width="12" height="12" fill="#c9a1a8"/>)}<circle cx={position[0]*24+12} cy={position[1]*24+12} r="7" fill="#bfe2e8"/>
    </svg><div className="rl-state"><div>STATE<strong>({position.join(', ')})</strong></div><div>ACTION<strong>{current?['UP','DOWN','LEFT','RIGHT'][current.action]:'START'}</strong></div><div>PACKAGES<strong>{current?.remaining??recording.packages.length}</strong></div><div>REWARD SUM<strong>{reward}</strong></div></div></div><div className="tool-controls"><button className="icon-button" title="Previous RL step" aria-label="Previous RL step" disabled={step===0} onClick={()=>{setPlaying(false);setStep(step-1);}}><ArrowLeft size={17}/></button><output aria-live="polite">{step} / {count}<span>{recording.trace_complete?'Recorded completed episode':'Bounded partial episode'}</span></output><button className="icon-button" title="Next RL step" aria-label="Next RL step" disabled={step===count} onClick={()=>{setPlaying(false);setStep(step+1);}}><ArrowRight size={17}/></button><button className="icon-button" title={reduced?'Reduced motion: manual steps remain available':running?'Pause trace':'Play trace'} aria-label={running?'Pause RL replay':'Play RL replay'} disabled={reduced} onClick={()=>{if(step===count)setStep(0);setPlaying(!running);}}>{running?<Pause size={17}/>:<Play size={17}/>}</button><button className="icon-button" title="Reset RL replay" aria-label="Reset RL replay" onClick={()=>{setStep(0);setPlaying(false);}}><RotateCcw size={17}/></button></div><p className="evidence-caption">Fresh 2026 execution of original Scenario1, last completed episode after the original training loop. Greedy argmax actions; stochastic mode may substitute another action with 20% probability. Rewards: blocked−15, package+80, other move−1. One seed/run per mode, not a success-rate or convergence evaluation. The supplied teaching environment stays private.</p><div className="q-update"><span>Q(s,a)</span><span>←</span><span>(1−α)Q(s,a) + α[r + γ max Q(s′,a′)]</span></div></div>;
}
