'use client';
import { useState } from 'react';
import { useDemoClock } from './demos/use-demo-clock';
import { DemoControls } from './demos/controls';
export function FourierLab() {
  const [harmonics,setHarmonics]=useState(1);
  const [playing,setPlaying]=useState(false);
  const {ref:demoRef,reduced,active}=useDemoClock(playing&&harmonics<17,900,()=>setHarmonics(n=>Math.min(17,n+2)));
  const values=Array.from({length:401},(_,i)=>{const t=-8+i*.04;let value=.5;for(let k=1;k<=harmonics;k+=2)value+=2/(k*Math.PI)*Math.sin(k*Math.PI*t/4);return {t,value,target:((t%8)+8)%8<4?1:0};});
  const path=(key:'value'|'target')=>values.map((v,i)=>`${i?'L':'M'}${i*1.4} ${145-v[key]*100}`).join(' ');
  return <div ref={demoRef} className="demo-instrument interactive-lab"><p className="eyebrow">EEE2047S / FOURIER RECONSTRUCTION</p><label htmlFor="harmonics">Maximum harmonic<strong>{harmonics}</strong></label><input id="harmonics" aria-label="Maximum Fourier harmonic" type="range" min="1" max="17" step="2" value={harmonics} onChange={e=>{setPlaying(false);setHarmonics(Number(e.target.value));}}/><svg className="waveform-chart" viewBox="0 0 560 200" role="img" aria-label={`Eight-second periodic pulse reconstructed through harmonic ${harmonics}`}>{Array.from({length:(harmonics+1)/2},(_,j)=>{const k=j*2+1;return <path key={k} d={values.map((v,i)=>`${i?'L':'M'}${i*1.4} ${145-(.5+2/(k*Math.PI)*Math.sin(k*Math.PI*v.t/4))*100}`).join(' ')} fill='none' stroke={j%2?'#ff719f':'#4d9bff'} opacity='.22'/>;})}<path d={path('target')} stroke="#e1c3a4" strokeDasharray="5 5" fill="none"/><path d={path('value')} className="signal-line"/><text x="5" y="192" fill="#a9c1ca" fontSize="12">−8 s</text><text x="270" y="192" fill="#a9c1ca" fontSize="12">0</text><text x="535" y="192" fill="#a9c1ca" fontSize="12">8 s</text></svg><DemoControls running={active} reduced={reduced} toggle={()=>{if(harmonics===17)setHarmonics(1);setPlaying(!playing);}} step={()=>{setPlaying(false);setHarmonics(n=>Math.min(17,n+2));}} reset={()=>{setPlaying(false);setHarmonics(1);}}/><p className='demo-status' role='status'>Odd harmonics through N = {harmonics}</p><pre className="code-evidence"><code>x_N(t) = 1/2 + Σ [2/(kπ)] sin(kπt/4), k odd</code></pre><p className="evidence-caption">New browser visualisation of the period 8, 0≤t&lt;4 pulse in completed Lab 2 Question 2. Dashed: ideal pulse; faint: individual harmonics with DC; solid: finite sum. Not a hardware measurement. Ringing near discontinuities remains.</p></div>;
}
