'use client';
import { useState } from 'react';
import { schedule, adcToCompare, type Job } from '@/lib/lab-models';

export function SchedulingLab() {
  const [policy,setPolicy]=useState<'FCFS'|'SJF'>('FCFS');
  const [jobs,setJobs]=useState<Job[]>([{id:'A',arrival:0,burst:7},{id:'B',arrival:0,burst:3},{id:'C',arrival:1,burst:2},{id:'D',arrival:2,burst:4}]);
  const timeline=schedule(jobs,policy); const end=timeline.at(-1)!.end;
  const average=(key:'waiting'|'response'|'turnaround')=>(timeline.reduce((sum,j)=>sum+j[key],0)/jobs.length).toFixed(2);
  const colours=['#afd3df','#d2c7aa','#a5c7ac','#beaabe'];
  return <div className="engineering-tool interactive-lab"><div className="lab-toolbar"><span className="eyebrow">NON-PREEMPTIVE SERVICE</span><div className="segmented" role="group" aria-label="Scheduling policy">{(['FCFS','SJF'] as const).map(p=><button key={p} aria-pressed={policy===p} onClick={()=>setPolicy(p)}>{p}</button>)}</div></div><div className="job-inputs">{jobs.map((j,i)=><div key={j.id}><strong>Request {j.id}</strong><label>Arrival<input aria-label={`Arrival ${j.id}`} type="number" min="0" max="16" value={j.arrival} onChange={e=>setJobs(jobs.map((v,k)=>k===i?{...v,arrival:Math.max(0,Math.min(16,Number(e.target.value)))}:v))}/></label><label>Service<input aria-label={`Service ${j.id}`} type="number" min="1" max="16" value={j.burst} onChange={e=>setJobs(jobs.map((v,k)=>k===i?{...v,burst:Math.max(1,Math.min(16,Number(e.target.value)))}:v))}/></label></div>)}</div><svg viewBox="0 0 600 100" className="gantt-chart" role="img" aria-label={`${policy} order ${timeline.map(j=>j.id).join(', ')}`}><line x1="20" x2="580" y1="72" y2="72" stroke="#69848f"/>{timeline.map(j=><g key={j.id}><rect x={20+j.start/end*560} y="15" width={j.burst/end*560} height="44" fill={colours[jobs.findIndex(x=>x.id===j.id)]}/><text x={20+(j.start+j.burst/2)/end*560} y="42" textAnchor="middle" fill="#142127">{j.id}</text><text x={20+j.start/end*560} y="89" fontSize="12" fill="#c4d5da">{j.start}</text></g>)}<text x="580" y="89" textAnchor="end" fill="#c4d5da" fontSize="12">{end}</text></svg><div className="lab-readouts"><div>WAITING<strong>{average('waiting')}</strong></div><div>RESPONSE<strong>{average('response')}</strong></div><div>TURNAROUND<strong>{average('turnaround')}</strong></div><div>THROUGHPUT<strong>{(jobs.length/(end-Math.min(...jobs.map(j=>j.arrival)))).toFixed(3)}</strong></div></div><p className="evidence-caption">Synthetic demonstration requests, arbitrary time units. A new scheduling visualisation, not historical measurements. Response equals waiting here because service is non-preemptive. The original Andre simulation&apos;s invalid timing aggregates remain disclosed.</p></div>;
}
export function EmbeddedLab() {
  const [adc,setAdc]=useState(2048);const compare=adcToCompare(adc);const duty=compare/48000;
  const points=Array.from({length:161},(_,i)=>`${i?'L':'M'}${i*3.5} ${i%40<duty*40?24:95}`).join(' ');
  return <div className="engineering-tool interactive-lab"><p className="eyebrow">ADC → TIM3 CCR3 → PWM</p><label htmlFor="adc-input">12-bit input<strong>{adc}</strong></label><input id="adc-input" aria-label="ADC input" type="range" min="0" max="4095" value={adc} onChange={e=>setAdc(Number(e.target.value))}/><div className="lab-readouts"><div>ADC RANGE<strong>0–4095</strong></div><div>ARR<strong>47999</strong></div><div>CCR3<strong>{compare}</strong></div><div>DUTY<strong>{(duty*100).toFixed(1)}%</strong></div></div><svg className="waveform-chart" viewBox="0 0 560 125" role="img" aria-label={`Ideal PWM at ${(duty*100).toFixed(1)} percent duty cycle`}><path d="M0 95 H560 M0 24 H560" className="chart-grid"/><path d={points} className="signal-line"/></svg><pre className="code-evidence"><code>CCR = (adc_value * (47999 + 1)) / 4095</code></pre><p className="evidence-caption">Portfolio interactive visualisation of the submitted integer mapping. Ideal PWM, not a hardware trace. Source: ADCtoCCR and TIM3 configuration. At maximum input CCR=48000 exceeds ARR and represents full duty. Nominal carrier: 8 MHz / 48000 ≈ 166.7 Hz, conditional on the documented clock.</p></div>;
}
export function ConcurrencyLab() {
  const [workers,setWorkers]=useState(4);
  return <div className="engineering-tool interactive-lab"><label htmlFor="worker-count">Worker partition<strong>{workers}</strong></label><input id="worker-count" type="range" min="1" max="4" value={workers} onChange={e=>setWorkers(Number(e.target.value))}/><svg viewBox="0 0 600 180" className="worker-chart" role="img" aria-label={`${workers} conceptual worker lanes`}><text x="10" y="20" fill="#bdd2db" fontSize="12">SEQUENTIAL</text>{[0,1,2,3].map(i=><rect key={i} x={30+i*135} y="30" width="125" height="18" fill="#93bdc8"/>)}<text x="10" y="75" fill="#bdd2db" fontSize="12">PARTITION / WORK / REDUCE</text>{Array.from({length:workers},(_,i)=><g key={i}><rect x="30" y={90+i*21} width={540/workers-10} height="14" fill={i%2?'#b8b995':'#9bbca7'}/><path d={`M${30+540/workers} ${97+i*21} H560 V173`} stroke="#6c8c9b" fill="none"/></g>)}</svg><p className="evidence-caption">Conceptual task lanes based on fork/join terrain search. Equal-length blocks are explanatory, not measured runtimes or a promised speedup. Shared visited-state contention and unseeded historical inputs limit direct comparisons.</p></div>;
}
